defaults:
  - base
  - _self_


evaluation:
  # CSV for path and metadata to training examples.
  csv_path: 
  name: null
  gpu_id: null  # CUDA GPU to use
  seed: 123
  nof_samples: 25

  # Directory of software, weights, and outputs.
  pt_hub_dir: ./.cache/torch/
  output_dir: ./evaluation_outputs/
  

  # Path to model weights.
  model_path: ./trained_models/mbd-ba


  diffusion:
    # Number of steps.
    num_t: 100
    # Analogous to sampling temperature.
    noise_scale: 0.0
    # Final t.
    min_t: 0.01


