# Default or base configuration for SE(3) diffusion experiments.

defaults:
  - override hydra/launcher: joblib
  - _self_

data:
  # CSV for path and metadata to training examples.
  csv_path: /home/klypar/Desktop/PPI3D/trainset_angle_100.csv
  test_csv_path: null
  split: 0.9
  min_t: 0.01
  num_t: 100

diffuser:
  diffuse_trans: True
  diffuse_rot: True

  # R(3) diffuser arguments
  r3:
    min_b: 0.1
    max_b: 20.0
    coordinate_scaling: 0.1

  # SO(3) diffuser arguments
  so3:
    num_omega: 1000
    num_sigma: 1000
    min_sigma: 0.01
    max_sigma: 1.0
    schedule: logarithmic
    cache_dir: .cache/
    use_cached_score: False

model:
  s_r_embed_size: 128
  z_rr_embed_size: 64
  dropout: 0.0
  embed:
    index_embed_size: 32
    restype_embed_size: 32
    num_bins: 22
    min_bin: 1e-5
    max_bin: 20.0
  ac:
    c_s: ${model.s_r_embed_size}
    c_z: ${model.z_rr_embed_size}
    c_hidden: 64
    no_heads: 12
    no_qk_points: 4
    no_v_points: 8
    c_hidden_cmct: 32
    c_hidden_mul: 32
    c_hidden_pair_att: 32
    no_heads_pair: 2
    transition_n: 2
    pair_dropout: 0.1
    c_resnet: 64
    no_resnet_blocks: 3
    no_angles: 6
    num_blocks: 4
    coordinate_scaling: ${diffuser.r3.coordinate_scaling}

    


experiment:
  # Experiment metadata
  name: baseline
  run_id: null

  #training mode
  use_ddp : False

  # Training arguments
  log_freq: 1000
  batch_size: 4
  num_loader_workers: 5
  num_epoch: 500
  learning_rate: 0.0001
  max_squared_res: 500000
  prefetch_factor: 100
  use_gpu: True
  num_gpus: 1
  sample_mode: time_batch

  # Wandb logging
  wandb_dir: ./
  use_wandb: False

  # How many steps to checkpoint between.
  ckpt_freq: 10000
  # Take early checkpoint at step 100. Helpful for catching eval bugs early.
  early_ckpt: True

  # Checkpoint directory to warm start from.
  warm_start: null
  use_warm_start_conf: False
  ckpt_dir: ./ckpt/

  # Loss weights.
  coordinate_scaling: ${diffuser.r3.coordinate_scaling}
  rr_dist_mat_loss_weight: 1.0
  rr_dist_mat_loss_t_filter: 1.0
  rp_dist_mat_loss_weight: 1.0
  rp_dist_mat_loss_t_filter: 1.0
  clash_loss_weight: 1.0
  clash_loss_t_filter: 0.5

  # Evaluation.
  eval_dir: ./eval_outputs
  noise_scale: 1.0
  nof_samples: 10
  # Filled in during training.
  num_parameters: null

hydra:
  sweeper:
    params:
      # Example of hydra multi run and wandb.
      experiment.name: use_wandb
      experiment.use_wandb: True
